version: '3'
 
services:
    nginx_img_1:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx_con_1
        build: ./nginx/1
        expose:
            - ${NGINX_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${NGINX_1_IP}

    nginx_img_2:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx_con_2
        build: ./nginx/2
        expose:
            - ${NGINX_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${NGINX_2_IP}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
